### ISSUE TITLE
Allow inputing beatmap over stdin.

### ISSUE THREAD

**Issue by ekgame** [Francesco149/oppai#11]
It would be useful to allow using oppai without having a physical beatmap file. The best solution for this would be to enable inputing the beatmap file data over stdin.

This would allow applications to have a more versatile way of interacting with oppai.

**Comment by omkelderman** [comment]
wait, how would you "inputing the beatmap file data over stdin" when you dont have the physical beatmap file? xd

**Comment by ekgame** [comment]
I could get raw data from osu! (Ex.: https://osu.ppy.sh/osu/975153) and pipe it right into oppai, without writing the file to disc.

**Comment by omkelderman** [comment]
ah like attaching the network-stream to stdin? sounds cool :P

**Comment by ekgame** [comment]
From console you could just do something like `curl https://osu.ppy.sh/osu/1018221 | oppai 99% -ojson` and get nice output.

**Comment by omkelderman** [comment]
yeah, thats what i meant, altho it'll probably end up looking something like `curl https://osu.ppy.sh/osu/1018221 | oppai - 99% -ojson` (`-` as file to say 'use stdin'), because how the commandline is parsed atm :stuck_out_tongue: (`beatmap::parse(argv[1], b);`)

**Comment by Francesco149** [comment]
yeah I was thinkin of adding piping for quicker use, will work on this when I can

**Comment by Tyrrrz** [comment]
I'd suggest leaving the GET to the application developers, because you never know how they implement it. For example, in my application I only need to download map once and then I use oppai to find PP values in different accuracy points.
However, an option to pass beatmap data as base64 would be helpful.

**Comment by ekgame** [comment]
Why base64? osu file format is already plaintext.

**Comment by Tyrrrz** [comment]
Base64 provides the convenience of encoding characters that can mess up command line string and it's pretty much the standard of transferring long set of bytes.

**Comment by omkelderman** [comment]
> I'd suggest leaving the GET to the application developers

thats exactly what we are suggesting, only thing we want is an option to tell oppai to read the data not from the `.osu` file, but from `stdin`. Thus enabling to do something like this in a linux command-prompt:

``` sh
curl https://osu.ppy.sh/osu/1018221 | ./oppai - 99% -ojson
```

instead of

``` sh
curl https://osu.ppy.sh/osu/1018221 -o file.osu
./oppai file.osu 99% -ojson
rm file.osu
```

> Base64 provides the convenience of encoding characters that can mess up command line string and it's pretty much the standard of transferring long set of bytes.

If its binary data sure, but
1. it's not binary data (it's plaintext)
2. it's not provided via commandline, but via either stdin (the new, nonexistent option) or a file (the current option)

**Comment by Tyrrrz** [comment]
Sorry, I misunderstood you then
