### ISSUE TITLE
[question] Monolithic build?

### ISSUE THREAD

**Issue by emmiegit** [Francesco149/oppai#30]
I was looking at the source and I couldn't help but wonder, why do you squash all of the sources into `main.cc` via includes rather than having separate object files with headers? Is there a design reason for this?

**Comment by Francesco149** [comment]
it's my preference to use a monolithic build. ideally at some point I would organize all the code good enough that I don't even need multiple files to make it readable.

with a small codebase it can also potentially speed up compile time slightly by not having the overhead of handling multiple compilation units.

another advantage is that I can declare every function as static and get warnings when any function is unused.

another massive advantage is that I can compile everything with a simple gcc / cl call without listing all the files and not have to depend on make or other build systems.

**Comment by emmiegit** [comment]
It is true that multiple compilation units slows compile times, especially for C++, but it is sort of a balance thing. At a certain point wouldn't the time cost of recompiling the entire project for a minor change offset that?

>another advantage is that I can declare every function as static and get warnings when any function is unused.

Never considered that. Interesting benefit.



>another massive advantage is that I can compile everything with a simple gcc / cl call without listing all the files and not have to depend on make or other build systems.

Is it really that inconvenient to have a small makefile? I certainly understand that any reduction of dependencies can increase portability, but if you use an old tool it shouldn't make that much of a difference. I have a hard time understanding how this is a big advantage.

**Comment by Francesco149** [comment]
separate compilation units would also make code more annoying to navigate and update for me - I would have to write header files for each unit and update the functions signatures one more place.

I know make can do incremental builds, but I don't really like them. it feels cleaner to rebuild, and well written code should compile almost instantly except for special cases like projects with millions of LOC.

oppai's compile time is already decent, and it might speed up further as I get rid of template usage.

and yes, I understand that these conventions are weird to most programmers, even C/C++ ones, but I know what I'm doing.

**Comment by omkelderman** [comment]
> and yes, I understand that these conventions are weird to most programmers, even C/C++ ones, but I know what I'm doing.

can confirm. I have no idea why someone would choose to do this tbh. But thats my personal opinion :smile:.

If im honest, maintaining this codebase for me would be annoying. But if it works for you, then go ham, luckily I am not a maintainer xD

One personal feeling I have: I dont get the "it compiles a tiny bit faster" argument. Who cares? the whole point of compiling is to do it once and have a binary and use it. Its not like that 1ms time gained during compile is gonna be that much of an influence during developing. Which is why incremental builds and build systems exist in the first place anyway.

But in the end, I dont care, oppai is an amazing peace of software, and if this is the way that works best, then I'm not gonna complain. Just sayin its not how I would do things. I would lose track of what I'm doing probably, idk xD

/my 2cents

**Comment by Francesco149** [comment]
I like software like DWM, where it's so quick and easy to compile that you can use the source code itself as a config file (which dwm does) and recompiling is as fast as editing and saving a config. that's where my mindset comes from.

**Comment by Francesco149** [comment]
but yeah, I've used makefiles and multiple compilation units in past project.
they just end up either annoying me or not adding anything useful at least for my kind of projects.
ill reopen this if I ever change coding style
